version: "3.7"

services:
  nameko-rabbit:
    image: rabbitmq:3
    ports:
      - "5672:5672"

  redis:
    image: redis
    ports: 
      - "6379:6379"

  airports:
    build:
      context: ./airports
    container_name: airports
    depends_on:
      - nameko-rabbit
      - redis
    network_mode: "host"

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    depends_on:
      - nameko-rabbit
      - redis
    network_mode: "host"

  trips:
    build:
      context: ./trips
    container_name: trips
    depends_on:
      - nameko-rabbit
      - redis
    network_mode: "host"
