version: "3.7"

services:
  nameko-rabbit:
    image: rabbitmq:3
    ports:
      - "5672:5672"

  redis:
    image: redis
    ports: 
      - "6379:6379"

  airport:
    build:
      context: ./airports
      # This is the network utilized only for the build.
      # Build fails if this is not specified in my case (might be my docker-compose configuration)
      network: host
    container_name: airports
    depends_on:
      - nameko-rabbit
      - redis

  gateway:
    build:
      context: ./gateway
      network: host
    container_name: gateway
    depends_on:
      - nameko-rabbit
      - redis
    ports:
      - "8000:8000"


  trip:
    build:
      context: ./trips
      network: host
    container_name: trips
    depends_on:
      - nameko-rabbit
      - redis
